apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtp-mailer.fullname" . }}
  labels:
    {{- include "smtp-mailer.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smtp-mailer.selectorLabels" . | nindent 4 }}
